# Generated by Django 4.1.2 on 2022-11-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=1000)),
                ('condition', models.CharField(max_length=1000)),
                ('second_condition', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=1000)),
                ('internal_storage', models.CharField(max_length=1000)),
                ('card_slot', models.CharField(max_length=1000)),
                ('main_camera', models.CharField(blank=True, max_length=1000)),
                ('selfie_camera', models.CharField(blank=True, max_length=1000)),
                ('operating_system', models.CharField(blank=True, max_length=1000)),
                ('color', models.CharField(max_length=1000)),
                ('battery_life', models.CharField(max_length=1000)),
                ('screen_size', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('contact', models.IntegerField()),
                ('about', models.TextField(blank=True)),
                ('picture_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('type_of_picture', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_directory', models.CharField(max_length=1000)),
                ('type_of_picture', models.CharField(max_length=1000)),
                ('original_height', models.IntegerField(blank=True, null=True)),
                ('original_width', models.IntegerField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ecom2.phone')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='ecom2.seller'),
        ),
    ]
