# Generated by Django 4.1.2 on 2022-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom2', '0002_alter_phone_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phoneimage',
            name='original_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneimage',
            name='original_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
