# Generated by Django 4.1.2 on 2022-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('con', 'consumable'), ('non-con', 'non-consumable')], default='non-con', max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('quantity', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
