# Generated by Django 4.1.2 on 2022-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_class',
            field=models.CharField(default='shoes', max_length=300),
            preserve_default=False,
        ),
    ]
