# Generated by Django 4.1.2 on 2022-11-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product_sub_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=99, null=True),
        ),
    ]
