# Generated by Django 4.1.2 on 2022-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='useroftodolist',
        ),
    ]
